.PHONY: clean All

All:
	@echo "----------Building project:[ mapreduce - Release ]----------"
	@cd "mapreduce" && "$(MAKE)" -f  "mapreduce.mk"
clean:
	@echo "----------Cleaning project:[ mapreduce - Release ]----------"
	@cd "mapreduce" && "$(MAKE)" -f  "mapreduce.mk" clean
